spring:
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
