spring:
  application:
    name: users
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:users
    driver-class-name: org.h2.Driver
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080
