###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "John Doe",
    "email": "john.doe@hotmail.com",
    "password": "123456"
}

###
GET http://localhost:8080/users